apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: notes
  namespace: deckhub
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - image: deckhub/notes:1.0.0-alpha1
        imagePullPolicy: Always
        name: notes
        env:
          - name: Runtime__PathBase
            value: '/notes'
          - name: Redis__Host
            value: 'redis'
          - name: Runtime__IdentityPathPrefix
            value: 'i'
          - name: AppMetrics__InfluxDbServer
            value: 'http://rlmetrics.eastus.cloudapp.azure.com:8086'
          - name: AppMetrics__InfluxDbDatabase
            value: 'deckhub'
          - name: ConnectionStrings__Notes
            valueFrom:
              secretKeyRef:
                name: notes-db
                key: connstr
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: notes
  namespace: deckhub
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: notes
  sessionAffinity: ClientIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: notes
  namespace: deckhub
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: deckhub.app
    http:
      paths:
      - path: /notes
        backend:
          serviceName: notes
          servicePort: 80
