apiVersion: batch/v1
kind: Job
metadata:
  name: notes-migrate
  namespace: deckhub
spec:
  template:
    metadata:
      name: notes-migrate
    spec:
      containers:
      - name: notes-migrate
        image: deckhub/notes-migrate:1.0.0-alpha1
        args: ["$(SECRET_CONNSTR)"]
        env:
          - name: SECRET_CONNSTR
            valueFrom:
              secretKeyRef:
                name: notes-db
                key: connstr
      restartPolicy: OnFailure