# Design-time dependencies

version: '3'

services:
  
  postgres:
    image: postgres:9.6.4
    environment:
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: secretsquirrel
    ports:
      - 5432:5432
