// <auto-generated />
using System;
using DeckHub.Notes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DeckHub.Notes.Migrate.Migrations
{
    [DbContext(typeof(NoteContext))]
    [Migration("20180509221714_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DeckHub.Notes.Data.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NoteText");

                    b.Property<bool>("Public");

                    b.Property<string>("SlideIdentifier")
                        .HasMaxLength(256);

                    b.Property<DateTimeOffset>("Timestamp");

                    b.Property<string>("UserHandle")
                        .HasMaxLength(16);

                    b.HasKey("Id");

                    b.HasIndex("UserHandle", "SlideIdentifier")
                        .IsUnique();

                    b.ToTable("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
